testing

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -84,6 +84,7 @@ jobs:
               echo "***"
               ls -R ./CommentAPITests/TestResults/**/coverage.opencover.xml
               echo "***"
+              cat ./CommentAPITests/TestResults/**/coverage.opencover.xml || echo "Coverage file not found."
 
   
         - name: Upload Coverage Report as Artifact
@@ -142,7 +143,10 @@ jobs:
         - name: Print the contents of the coverage report
           run: |
             echo "Printing the contents of coverage.opencover.xml:"
-            cat ./coverage-report/coverage.opencover.xml || echo "Coverage file not found."
+            cat ./coverage-report/**/coverage.opencover.xml || echo "Coverage file not found."
+            echo "***"
+            cat ./coverage-report/**/coverage.opencover.xml || echo "Coverage file not found."
+
           shell: bash
 
         - name: Install SonarScanner
@@ -156,7 +160,7 @@ jobs:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           run: |
-            dotnet sonarscanner begin /k:"OlivierMantz_CommentAPI" /o:"oliviermantz" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="coverage-report/coverage.opencover.xml" /d:sonar.exclusions="**/Migrations/*.cs,**/*.js,**/*.css" /d:sonar.verbose=true
+            dotnet sonarscanner begin /k:"OlivierMantz_CommentAPI" /o:"oliviermantz" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="coverage-report/**/coverage.opencover.xml" /d:sonar.exclusions="**/Migrations/*.cs,**/*.js,**/*.css" /d:sonar.verbose=true
               
         - name: Restore NuGet packages
           run: dotnet restore  
