testing

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -24,7 +24,7 @@ jobs:
                   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                   DISABLE_ERRORS: true
 
-    build:
+    build_and_sonarcloud_analysis:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout Repository
@@ -47,8 +47,7 @@ jobs:
         - name: Build
           run: dotnet build --configuration Release --no-restore
   
-        # SonarCloud Analysis
-        - name: Set up JDK 17 (for SonarCloud)
+        - name: Set up JDK 17 for SonarCloud
           uses: actions/setup-java@v3
           with:
             java-version: 17
@@ -65,16 +64,17 @@ jobs:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           run: |
-            dotnet sonarscanner begin /k:"OlivierMantz_CommentAPI" /o:"oliviermantz" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.cobertura.xml" /d:sonar.exclusions="**/Migrations/*.cs,**/*.js,**/*.css" /d:sonar.verbose=true
+            dotnet sonarscanner begin /k:"OlivierMantz_CommentAPI" /o:"oliviermantz" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.cobertura.xml" /d:sonar.exclusions="**/Migrations/*.cs,**/*.js,**/*.css" /d:sonar.verbose=true
   
         - name: End SonarCloud Scan
           env:
             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           run: |
             dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
+      
 
     test:
-      needs: build
+      needs: build_and_sonarcloud_analysis
       runs-on: ubuntu-latest
       steps:
         - name: Checkout Repository
@@ -127,59 +127,59 @@ jobs:
                   push: true
                   tags: ${{ secrets.DOCKERHUB_USERNAME }}/comment_api:main
                   
-    # sonarcloud_analysis:
-    #   needs: test
-    #   runs-on: windows-latest
-    #   steps:
-    #     - name: Set up JDK 17
-    #       uses: actions/setup-java@v3
-    #       with:
-    #         java-version: 17
-    #         distribution: 'zulu'
+    sonarcloud_analysis:
+      needs: test
+      runs-on: windows-latest
+      steps:
+        - name: Set up JDK 17
+          uses: actions/setup-java@v3
+          with:
+            java-version: 17
+            distribution: 'zulu'
     
-    #     - name: Checkout code
-    #       uses: actions/checkout@v3
-    #       with:
-    #         fetch-depth: 0
-    #     - name: Download Code Coverage Results
-    #       uses: actions/download-artifact@v3
-    #       with:
-    #         name: code-coverage
-    #         path: .  
+        - name: Checkout code
+          uses: actions/checkout@v3
+          with:
+            fetch-depth: 0
+        - name: Download Code Coverage Results
+          uses: actions/download-artifact@v3
+          with:
+            name: code-coverage
+            path: .  
 
-    #     - name: List contents of the directory
-    #       run: |
-    #         echo "Listing contents of the downloaded artifacts directory:"
-    #         ls 
+        - name: List contents of the directory
+          run: |
+            echo "Listing contents of the downloaded artifacts directory:"
+            ls 
 
-    #     - name: Print the contents of the coverage report
-    #       run: |
-    #         echo "Printing the contents of coverage.cobertura.xml:"
-    #         cat ./coverage.cobertura.xml || echo "Coverage file not found."
-    #       shell: bash
+        - name: Print the contents of the coverage report
+          run: |
+            echo "Printing the contents of coverage.cobertura.xml:"
+            cat ./coverage.cobertura.xml || echo "Coverage file not found."
+          shell: bash
 
 
-    #     - name: Install SonarScanner
-    #       run: |
-    #         dotnet tool install --global dotnet-sonarscanner
-    #         echo "Adding .NET global tools to PATH..."
-    #         echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
+        - name: Install SonarScanner
+          run: |
+            dotnet tool install --global dotnet-sonarscanner
+            echo "Adding .NET global tools to PATH..."
+            echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
     
-    #     - name: Begin SonarCloud Scan
-    #       env:
-    #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-    #       run: |
-    #         dotnet sonarscanner begin /k:"OlivierMantz_CommentAPI" /o:"oliviermantz" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.cobertura.xml" /d:sonar.exclusions="**/Migrations/*.cs,**/*.js,**/*.css" /d:sonar.verbose=true
+        - name: Begin SonarCloud Scan
+          env:
+            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          run: |
+            dotnet sonarscanner begin /k:"OlivierMantz_CommentAPI" /o:"oliviermantz" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.cobertura.xml" /d:sonar.exclusions="**/Migrations/*.cs,**/*.js,**/*.css" /d:sonar.verbose=true
     
-    #     - name: Restore NuGet packages
-    #       run: dotnet restore  
+        - name: Restore NuGet packages
+          run: dotnet restore  
 
-    #     - name: Build
-    #       run: dotnet build --configuration Release --no-restore
+        - name: Build
+          run: dotnet build --configuration Release --no-restore
     
-    #     - name: End SonarCloud Scan
-    #       env:
-    #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-    #       run: |
-    #         dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
+        - name: End SonarCloud Scan
+          env:
+            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          run: |
+            dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
