testings

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -54,39 +54,64 @@ jobs:
                   path: |
                       CommentAPI/bin/Release/net7.0/
                       CommentAPITests/bin/Release/net7.0/
-
     test:
       needs: build
       runs-on: ubuntu-latest
       steps:
         - name: Checkout Repository
           uses: actions/checkout@v4
-    
+
         - name: Setup .NET Core SDK
           uses: actions/setup-dotnet@v2
           with:
             dotnet-version: "7.0.x"
-    
+
         - name: Download Build Artifacts
           uses: actions/download-artifact@v3
           with:
             name: built-app
             path: .
-    
-        - name: Install dotnet-coverage
-          run: dotnet tool install --global dotnet-coverage
-    
-        - name: Run Tests with dotnet-coverage
-          run: dotnet-coverage collect 'dotnet test --no-build' -f xml -o coverage.xml
-    
+
+        - name: Test and Collect Coverage
+          run: dotnet test ./CommentAPITests/CommentAPITests.csproj --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
+                  
+        - name: Print Current Working Directory
+          run: |
+              ls /home/runner/work/CommentAPI/CommentAPI/CommentAPITests/
+              echo "***"
+              ls -R ./CommentAPITests/TestResults
+              echo "***"
+              ls -R ./CommentAPITests/TestResults/**/coverage.opencover.xml
+              echo "***"
+              cat ./CommentAPITests/TestResults/**/coverage.opencover.xml || echo "Coverage file not found."
+  
         - name: Upload Coverage Report as Artifact
           uses: actions/upload-artifact@v3
           with:
             name: code-coverage
-            path: coverage.xml
-                      
+            path: ./CommentAPITests/TestResults/**/coverage.opencover.xml
           
-    
+    publish_to_dockerhub:
+        needs: [test]
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout Repository
+              uses: actions/checkout@v4
+
+            - name: Login to Docker Hub
+              uses: docker/login-action@v3
+              with:
+                  username: ${{ secrets.DOCKERHUB_USERNAME }}
+                  password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+            - name: Publish - Build and push Docker image
+              uses: docker/build-push-action@v5
+              with:
+                  context: .
+                  file: ./CommentAPI/Dockerfile
+                  push: true
+                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/comment_api:main
+                  
     sonarcloud_analysis:
       needs: test
       runs-on: windows-latest
@@ -101,53 +126,49 @@ jobs:
           uses: actions/checkout@v3
           with:
             fetch-depth: 0
-    
         - name: Download Code Coverage Results
           uses: actions/download-artifact@v3
           with:
             name: code-coverage
             path: coverage-report
-    
+          
+        - name: List contents of the directory
+          run: |
+            echo "Listing contents of the downloaded artifacts directory:"
+            ls coverage-report
+            echo "***"
+        - name: Print the contents of the coverage report
+          run: |
+            echo "Printing the contents of coverage.opencover.xml:"
+            cat ./coverage-report/**/coverage.opencover.xml || echo "Coverage file not found."
+            echo "***"
+          shell: bash
+
+        - name: Print Start of Coverage Report
+          run: head -n 100 ./coverage-report/**/coverage.opencover.xml || echo "Coverage report not found."
+
+
         - name: Install SonarScanner
-          run: dotnet tool install --global dotnet-sonarscanner
+          run: |
+            dotnet tool install --global dotnet-sonarscanner
+            echo "Adding .NET global tools to PATH..."
+            echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
     
         - name: Begin SonarCloud Scan
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          run: dotnet sonarscanner begin /k:"OlivierMantz_CommentAPI" /o:"oliviermantz" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml" /d:sonar.exclusions="**/Migrations/*.cs,**/*.js,**/*.css" /d:sonar.verbose=true
-    
+          run: |
+            dotnet sonarscanner begin /k:"OlivierMantz_CommentAPI" /o:"oliviermantz" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/**/coverage.opencover.xml" /d:sonar.exclusions="**/Migrations/*.cs,**/*.js,**/*.css" /d:sonar.verbose=true
+              
         - name: Restore NuGet packages
           run: dotnet restore  
-    
+
         - name: Build
           run: dotnet build --configuration Release --no-restore
     
         - name: End SonarCloud Scan
           env:
             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
-
-                  
-
-
-    publish_to_dockerhub:
-      needs: [test]
-      runs-on: ubuntu-latest
-      steps:
-          - name: Checkout Repository
-            uses: actions/checkout@v4
-
-          - name: Login to Docker Hub
-            uses: docker/login-action@v3
-            with:
-                username: ${{ secrets.DOCKERHUB_USERNAME }}
-                password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-          - name: Publish - Build and push Docker image
-            uses: docker/build-push-action@v5
-            with:
-                context: .
-                file: ./CommentAPI/Dockerfile
-                push: true
-                tags: ${{ secrets.DOCKERHUB_USERNAME }}/comment_api:main
+          run: |
+            dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
