testing

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -145,9 +145,11 @@ jobs:
             echo "Printing the contents of coverage.opencover.xml:"
             cat ./coverage-report/**/coverage.opencover.xml || echo "Coverage file not found."
             echo "***"
-            cat ./coverage-report/**/coverage.opencover.xml || echo "Coverage file not found."
-
           shell: bash
+
+        - name: Print Start of Coverage Report
+          run: head -n 100 ./coverage-report/**/coverage.opencover.xml || echo "Coverage report not found."
+
 
         - name: Install SonarScanner
           run: |
@@ -160,7 +162,7 @@ jobs:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           run: |
-            dotnet sonarscanner begin /k:"OlivierMantz_CommentAPI" /o:"oliviermantz" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="coverage-report/**/coverage.opencover.xml" /d:sonar.exclusions="**/Migrations/*.cs,**/*.js,**/*.css" /d:sonar.verbose=true
+            dotnet sonarscanner begin /k:"OlivierMantz_CommentAPI" /o:"oliviermantz" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/**/coverage.opencover.xml" /d:sonar.exclusions="**/Migrations/*.cs,**/*.js,**/*.css" /d:sonar.verbose=true
               
         - name: Restore NuGet packages
           run: dotnet restore  
